/*
Consider a logging system, where the timestamped log messages are generated by many application threads and are written into the log file by a server thread (logger). The requirement is to have the log messages sorted in chronological order. 







Can pipe be used between the application threads and the logger thread? Are there better ways to achieve this?
*/

